### ISSUE TITLE
首次发布时手机扫描无法进行授权

### ISSUE THREAD

**Issue by bajie-git** [digshare/digshare-script#1]
授权按钮是灰色的，界面没有可选项
![f3a39548bb83b8199f6319f957cb18b9](https://github.com/digshare/digshare-script/assets/63085735/b2fa277e-adce-4019-b043-981b2111259a)

**Comment by vilicvane** [comment]
@bajie-git 应该是需要先创建平道后再授权脚本哦。

**Comment by bajie-git** [comment]
> @bajie-git 应该是需要先创建平道后再授权脚本哦。

感谢，创建频道后可以了
我按照快速上手文档弄得  不知道还有这一步

**Comment by vilicvane** [comment]
@bajie-git 好的谢谢反馈～
